### ISSUE TITLE
gitlab-shell ignores git-hooks

### ISSUE THREAD

**Issue by rikur** [gitlabhq/gitlab-shell#123]
I modified hooks/update to reinforce certain naming conventions on our tag names, but gitlab-shell still allows users to create tags with any name. It looks to be that gitlab-shell invokes direct system calls:

```ruby
  def create_tag
    tag_name = ARGV.shift
    ref = ARGV.shift || "HEAD"
    cmd = %W(git --git-dir=#{full_path} tag -- #{tag_name} #{ref})
    system(*cmd)
  end

  def rm_tag
    tag_name = ARGV.shift
    cmd = %W(git --git-dir=#{full_path} tag -d #{tag_name})
    system(*cmd)
  end
```

And thus the update hook never gets called. Also, gitlabhq uses gitlab-shell to create tags and **users are able to bypass the constraints of my hooks/update via the gitlabhq UI.**

It would be PITA to maintain separate logic for these rules.

Could the satellites be used to mimic a real push to trigger the hook(s)?

**Comment by Aethylred** [comment]
Have you used the new customhooks?

http://doc.gitlab.com/ce/hooks/custom_hooks.html

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
